# Generated by Django 3.2.7 on 2021-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('negative_header', models.CharField(max_length=200)),
            ],
        ),
    ]
